force-app/main/default/objects/Book__c/fields/Serial_number__c.field-meta.xml
<CustomField>
    <fullName>Serial_number__c</fullName>
    <description>Unique serial number for each Book in format: AA-0-A-0000</description>
    <label>Serial number</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BooksHandler.cls
public with sharing class BooksHandler {
    private List<Book__c> getAllBooks() {
        List<Book__c> bookList = new List<Book__c>([SELECT Id, Name, Serial_number__c, Warehouse__c FROM Book__c]);
        return bookList;
    }

    public void assignBookSerialNumber() {
        List<Book__c> allBooks = getAllBooks();
        for (Integer i = 0, j = allBooks.size(); i < j; i++) {
            allBooks[i].Serial_number__c = 'AA-0-A-' + i;
            System.debug(allBooks[i].Serial_number__c);
        }
        if (!allBooks.isEmpty()) {
            update allBooks;
        }
    }
}