force-app/main/default/objects/Book__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataCreatorTest.cls
@isTest
private class DataCreatorTest {
    @IsTest
    static void testInsertDataAsUserWithoutPermissions() {
        List<Book__c> preInsertBookList = new List<Book__c>([SELECT Id FROM Book__c]);
        List<Warehouse__c> preInsertWarehouseList = new List<Warehouse__c>([SELECT Id FROM Warehouse__c]);
        String uniqueUserName = 'newuser' + DateTime.now().getTime() + '@testorg.com';
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Test Profile'];
        User u = new User(
            Alias = 'standt',
            Email = 'standarduser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = uniqueUserName
        );
        Test.startTest();
        System.runAs(u) {
            System.debug('Running test as user: ' + UserInfo.getUserName());
            System.debug('preInsertBookList size: ' + preInsertBookList.size());
            System.debug('preInsertWarehouseList size: ' + preInsertWarehouseList.size());
            DataCreator dc = new DataCreator();
            dc.createData(10);
        }
        Test.stopTest();
        List<Book__c> postInsertBookList = new List<Book__c>([SELECT Id FROM Book__c]);
        List<Warehouse__c> psotInsertWarehouseList = new List<Warehouse__c>([SELECT Id FROM Warehouse__c]);
        System.debug('postInsertBookList size: ' + postInsertBookList.size());
        System.debug('postInsertWarehouseList size: ' + psotInsertWarehouseList.size());
        System.assertEquals(preInsertBookList.size(), postInsertBookList.size(), 'Books records shouldn`t be created');
        System.assertEquals(
            preInsertWarehouseList.size(),
            psotInsertWarehouseList.size(),
            'Warehouses records shouldn`t be created'
        );
    }
}