force-app/main/default/objects/Book__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Number_of_books__c.field-meta.xml
<CustomField>
    <fullName>Number_of_books__c</fullName>
    <label>Number of books</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WarehouseHandler.cls
public with sharing class WarehouseHandler {
    private List<Warehouse__c> getAllWarehouses() {
        List<Warehouse__c> warehouses = new List<Warehouse__c>([SELECT Id, Name, Number_of_books__c FROM Warehouse__c]);
        return warehouses;
    }

    // Calculate number of books for each warehouse
    public void calculateBookAmount() {
        List<Warehouse__c> warehouses = getAllWarehouses();
        Set<Id> bookIds = new Set<Id>();

        AggregateResult[] groupedResults = [
            SELECT COUNT(Id), Warehouse__c
            FROM Book__c
            GROUP BY Warehouse__c
            ORDER BY COUNT(Id) DESC
        ];
        for (AggregateResult ar : groupedResults) {
            System.debug('Warehouse: ' + ar.get('Warehouse__c'));
            System.debug('Books: ' + ar.get('expr0'));
        }
    }
}